# Generated by Django 6.0.7 on 2026-07-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Brute Force Attack, Phishing Attempt', max_length=200)),
                ('detector', models.CharField(default='Signature Matching', help_text='e.g., Firewall, NIDS, Antivirus', max_length=100)),
                ('access_vector', models.CharField(default='Network', help_text='e.g., Local, Network, Physical', max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('is_false_positive', models.BooleanField(default=False, verbose_name='Mark as False Positive')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
